from typing import List, Protocol
from uuid import UUID

from domain.entities.wallet_entity import WalletEntity


class WalletRepository(Protocol):
    def get_wallet_by_id(self, wallet_id: UUID) -> WalletEntity: ...
    def create_wallet(self, wallet: WalletEntity) -> WalletEntity: ...
    def update_wallet_by_id(self, wallet_id: UUID) -> WalletEntity: ...
    def delete_wallet_by_id(self, wallet_id: UUID) -> WalletEntity: ...
    def list_all_wallets(self) -> List[WalletEntity]: ...
